#include "hysteria2_configurator.h"

#include "containers/containers_defs.h"
#include "core/controllers/serverController.h"
#include "core/scripts_registry.h"
#include "logger.h"

namespace {
Logger logger("Hysteria2Configurator");
}

Hysteria2Configurator::Hysteria2Configurator(std::shared_ptr<Settings> settings,
                                              const QSharedPointer<ServerController> &serverController, QObject *parent)
    : ConfiguratorBase(settings, serverController, parent)
{
}

QString Hysteria2Configurator::createConfig(const ServerCredentials &credentials, DockerContainer container,
                                             const QJsonObject &containerConfig, ErrorCode &errorCode)
{
    // Pull the password generated by configure_container.sh off the server.
    QString password = m_serverController->getTextFileFromContainer(
        container, credentials, amnezia::protocols::hysteria2::passwordPath, errorCode);
    if (errorCode != ErrorCode::NoError || password.isEmpty()) {
        logger.error() << "Failed to read hysteria2_password.key from server";
        if (errorCode == ErrorCode::NoError) {
            errorCode = ErrorCode::InternalError;
        }
        return "";
    }
    password.replace("\n", "").replace("\r", "");
    password = password.trimmed();

    // Pull the masquerade host the server actually used. If it's missing
    // (e.g. fresh install on an older container), fall back to the configured
    // value, then to the default. SNI mismatch with the server's self-signed
    // cert isn't a problem here — we use insecure: true client-side — but we
    // still want the client to *advertise* a believable SNI.
    QString masquerade = m_serverController->getTextFileFromContainer(
        container, credentials, amnezia::protocols::hysteria2::masqueradeHostPath, errorCode);
    masquerade.replace("\n", "").replace("\r", "");
    masquerade = masquerade.trimmed();
    if (errorCode != ErrorCode::NoError || masquerade.isEmpty()) {
        masquerade = containerConfig.value(config_key::site)
                         .toString(protocols::hysteria2::defaultMasqueradeHost);
    }
    errorCode = ErrorCode::NoError;

    // Pull the salamander obfs password (generated alongside the auth password).
    // Client and server must share it; without obfs the handshake is plain QUIC
    // and gets dropped by RKN/TSPU on a flagged server IP.
    QString obfsPassword = m_serverController->getTextFileFromContainer(
        container, credentials, amnezia::protocols::hysteria2::obfsPasswordPath, errorCode);
    obfsPassword.replace("\n", "").replace("\r", "");
    obfsPassword = obfsPassword.trimmed();
    if (errorCode != ErrorCode::NoError || obfsPassword.isEmpty()) {
        logger.error() << "Failed to read hysteria2_obfs_password.key from server";
        if (errorCode == ErrorCode::NoError) {
            errorCode = ErrorCode::InternalError;
        }
        return "";
    }
    errorCode = ErrorCode::NoError;

    // genVarsForScript already injects $HYSTERIA_SERVER_PORT,
    // $HYSTERIA_LOCAL_PROXY_PORT, $HYSTERIA_MASQUERADE_HOST and $SERVER_IP_ADDRESS.
    // We override the masquerade var with the server-confirmed value, and add
    // the password placeholders.
    ServerController::Vars vars = m_serverController->genVarsForScript(credentials, container, containerConfig);
    for (auto &v : vars) {
        if (v.first == QStringLiteral("$HYSTERIA_MASQUERADE_HOST")) {
            v.second = masquerade;
        }
    }
    vars.append({ QStringLiteral("$HYSTERIA_PASSWORD"), password });
    vars.append({ QStringLiteral("$HYSTERIA_OBFS_PASSWORD"), obfsPassword });

    QString config = m_serverController->replaceVars(
        amnezia::scriptData(ProtocolScriptType::hysteria2_template, container), vars);

    if (config.isEmpty()) {
        logger.error() << "Hysteria 2 template rendered to empty config";
        errorCode = ErrorCode::InternalError;
        return "";
    }

    logger.info() << "Hysteria 2 client config created";
    return config;
}
