#!/bin/bash

# AnyTLS startup. Reads the password generated by configure_container.sh and
# execs anytls-server with the right listen address.

echo "Container startup"

if command -v iptables >/dev/null 2>&1; then
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -A INPUT -p icmp -j ACCEPT
    if [ -n "${ANYTLS_SERVER_PORT:-}" ]; then
        iptables -A INPUT -p tcp --dport "$ANYTLS_SERVER_PORT" -j ACCEPT
    fi
    iptables -P INPUT DROP
fi

if command -v ip6tables >/dev/null 2>&1; then
    ip6tables -A INPUT -i lo -j ACCEPT
    ip6tables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    ip6tables -A INPUT -p ipv6-icmp -j ACCEPT
    ip6tables -P INPUT DROP
fi

killall -KILL anytls-server 2>/dev/null || true

PASSWORD_FILE="/opt/amnezia/anytls/anytls_password.key"
if [ -f "$PASSWORD_FILE" ] && [ -n "${ANYTLS_SERVER_PORT:-}" ]; then
    PASSWORD="$(tr -d '\r\n ' < "$PASSWORD_FILE")"
    exec anytls-server -l "0.0.0.0:${ANYTLS_SERVER_PORT}" -p "$PASSWORD"
fi

# No config yet — idle so install pipeline can drop files.
tail -f /dev/null
